"""empty message

Revision ID: 10750521c63f
Revises: 4f9fb763346b
Create Date: 2019-12-06 21:59:58.870400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10750521c63f'
down_revision = '4f9fb763346b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'seeking_tablent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_tablent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
